trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: javascriptdocker
    dockerfile: '**/Dockerfile'
    containerRegistry: 'acr'
    tags: |
       latest
