trigger: 
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    containerRegistry: 'tratonacr'
    repository: 'dockerImage'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      late
      ver1
