apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: springboot
  name: javascript
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: javascriptdocker.azurecr.io/javascriptdocker:latest
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboot
  name: java-lb
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: springboot
